## Lab 5

In this lab we will using python for image processing using Computer vision library. As you might have already seen that computer vision based technologies for to mechanical/aerospace problems such Autnomous Maneurs/Control. These technologies are based on image based operations and generally working on huge data sets. Feature extractions or data processing needs to performed on these data sets.


Based on paradigm of introduced in Lecture 5 i.e Serialization of data and use of external application API, We will be extracting the features of images for feeding to the Machine learningn API for making predictions. In this lab we will only perfrom tasks related to feature extraction.

Our data sets consitute of flow simulation snapshots at regular time steps. We have some flow simulation images and we wil create functions to crop the images by triminng the extra part.  Second we have to create a function for extracting the edges in the imgaes. Which in our case will shows the boundary of wake. So using the python we will caculating the wake size for that you need to write a function for curve integration.



## Task 1
Folder **pics** contains images, image names cotains Reynolds number and time. Create a class with relevants attribute for extracting and storing the Reynolds number, time and name of each file.

## Task 2
Crop the images for removing the extra part other than the flow domain. Store all the cropped images in the details. As you know, the images are just a matrix. So you need to extend your class for storing the matrix. Store only the black and white channel.

In [1]:
# Import packages
import cv2
import numpy as np
 
img = cv2.imread('d:\courses\SG\Automate-Python\Laboratories\Lab5\pics\\Re_140_t_0000.png')
print(img.shape) # Print image shape
cv2.imshow("original", img)
 
# Cropping an image
cropped_image = img[350:680, 650:1230]
 
# Display cropped image
cv2.imshow("cropped", cropped_image)
 
# Save the cropped image

cv2.imwrite("Cropped Image.jpg", cropped_image)
 
# print the image matrix
print(cropped_image)

 
# Convert to grayscale
gray = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)

# Gray scale of Cropped image
cv2.imshow("cropped", gray)

(902, 2072, 3)
[[[  0 182 200]
  [  0 182 200]
  [  0 182 200]
  ...
  [  0 182 200]
  [  0 182 200]
  [  0 182 200]]

 [[  0 182 200]
  [  0 182 200]
  [  0 182 200]
  ...
  [  0 182 200]
  [  0 182 200]
  [  0 182 200]]

 [[  0 182 200]
  [  0 182 200]
  [  0 182 200]
  ...
  [  0 182 200]
  [  0 182 200]
  [  0 182 200]]

 ...

 [[110  87  82]
  [110  87  82]
  [110  87  82]
  ...
  [110  87  82]
  [110  87  82]
  [110  87  82]]

 [[110  87  82]
  [110  87  82]
  [110  87  82]
  ...
  [110  87  82]
  [110  87  82]
  [110  87  82]]

 [[110  87  82]
  [110  87  82]
  [110  87  82]
  ...
  [110  87  82]
  [110  87  82]
  [110  87  82]]]


: 

In [ ]:
# Place for solution for task 2


## Task 2
Now retrieve the data of cropped images for extracting the edges of the boundary. Below are code snippets for edge extraction of images.

In [ ]:
# Hope you have already working python computer vision which you can check by importing it. 


import cv2
import numpy as np
import cv2

# Load image
img = cv2.imread'd:\courses\SG\Automate-Python\Laboratories\Lab5\pics\\Re_140_t_0000.png')

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Gaussian blur to reduce noise
blur = cv2.GaussianBlur(gray, (5,5), 0)

# Apply Canny edge detection algorithm with threshold values of 100 and 200
edges = cv2.Canny(blur, 100, 200)

# Display the original image and the edge detection result
cv2.imshow('Original Image', img)
cv2.imshow('Edges', edges)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# Place for solution ofr task 3

## Task 4
Now create a function for measuring the intensity of wake in the flow field. For that you need to integrate the edges obtained from the previous function. 